FROM ubuntu

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libc6-dev \
        gcc \ 
        make \
        cmake \
        valgrind \
        cppcheck \
    && rm -rf /var/lib/apt/lists/*
